### ISSUE TITLE
Tracking issue for small community-oriented tasks for the project

### ISSUE THREAD

**Issue by mjhouse** [mjhouse/deaf#7]
These tasks are necessary for building an open source community, but aren't directly tied to a feature or code change.

- [x] Add a Contributing guide
- [x] Add a Code of Conduct
- [x] Write "Your First Code Contribution" section in the Contributing guide (or remove)
- [x] Write "Improving The Documentation" section in the Contributing guide (or remove)
- [x] Add templates for issues
- [ ] ~Write "Commit Messages" section for the Contributing guide (or remove)~
- [x] Write "Join The Project Team" section for the Contributing guide (or remove)
- [ ] ~Add more extensive style guide (other than commit messages in the Contrib guide)~

* [Contribution Guide](https://github.com/mjhouse/deaf/blob/master/CONTRIBUTING.md)
* [Code of Conduct](https://github.com/mjhouse/deaf/blob/master/CODE_OF_CONDUCT.md)

**Comment by mjhouse** [comment]
Did most of this, decided against writing an extensive style guide until there are more contributors.
