### ISSUE TITLE
Create a project roadmap for future development

### ISSUE THREAD

**Issue by mjhouse** [mjhouse/deaf#8]
This will involve some thought and research, but generally:

* Figure out a rough feature set that I would consider 1.0.0
* Create between 2 and 4 milestones to achieve 1.0.0
* Break milestones down into issues on the backlog

There will be a number of other issues necessary for an open source project but not directly tied to a particular feature- things like adding `good-first-task` labels and a CONTRIBUTION.md file. Those will be enumerated in #7.

**Comment by mjhouse** [comment]
- [x] A file header, including all fields, can be read/written from/to an ELF file
    - [x] magic
    - [x] ei_class
    - [x] ei_data
    - [x] ei_version
    - [x] ei_osabi
    - [x] ei_abiversion
    - [x] ei_pad
    - [x] e_type
    - [x] e_machine
    - [x] e_version
    - [x] e_entry
    - [x] e_phoff
    - [x] e_shoff
    - [x] e_flags
    - [x] e_ehsize
    - [x] e_phentsize
    - [x] e_phnum
    - [x] e_shentsize
    - [x] e_shnum
    - [x] e_shstrndx
- [x] All program headers, including all fields, can be read/written from/to an ELF file
    - [x] p_type
    - [x] p_flags
    - [x] p_offset
    - [x] p_vaddr
    - [x] p_paddr
    - [x] p_filesz
    - [x] p_memsz
    - [x] p_align
- [x] All section headers, including all fields, can be read/written from/to an ELF file
    - [x] sh_name
    - [x] sh_type
    - [x] sh_flags
    - [x] sh_address
    - [x] sh_offset
    - [x] sh_size
    - [x] sh_link
    - [x] sh_info
    - [x] sh_addralign
    - [x] sh_entsize
- [x] All sections can be parsed from a file
- [ ] Array items can be parsed from sections that are arrays
    - [x] addresses
- [ ] Sections that are arrays can be converted to array structs containing array items
    - [x] Init array
    - [ ] Preinit array
    - [x] Fini array 
- [x] Table items can be parsed from sections that are tables
    - [x] String items
    - [x] Symbol items
    - [x] Relocation items
    - [ ] Hash items (?) 
- [ ] Sections that are tables can be converted to table structs containing table items
    - [x] String table
    - [x] Symbol table
    - [ ] Dynamic symbol table
    - [x] Relocation table
    - [x] Relocation addend table
    - [ ] Hash table 
 - [ ] Symbols that are functions can be used to access function data
